obs_column_label_0 = None

obs_column_label_1 = [
    'RRdiast(ABP) max',
    'RRdiast(ABP) mean',
    'RRdiast(ABP) min',
    'RRdiast(ABP) std',
    'RRdiast (NIBP) max',
    'RRdiast (NIBP) mean',
    'RRdiast (NIBP) min',
    'RRdiast (NIBP) std',
    'RRmean (ABP) max',
    'RRmean (ABP) mean',
    'RRmean (ABP) min',
    'RRmean (ABP) std',
    'RRmean (NIBP) max',
    'RRmean (NIBP) mean',
    'RRmean (NIBP) min',
    'RRmean (NIBP) std',
    'Leukozyten max',
    'Leukozyten mean',
    'Leukozyten min',
    'Leukozyten std',
    'Heartrate max',
    'Heartrate mean',
    'Heartrate min',
    'Heartrate std',
    'Respiratory Rate resp max',
    'Respiratory Rate resp mean',
    'Respiratory Rate resp min',
    'Respiratory Rate resp std',
    'Noradrenaline (Norepinefrine) max',
    'Thrombozyten max',
    'Thrombozyten mean',
    'Thrombozyten min',
    'Trombozyten std',
    'Noradrenaline (Norepinefrine) sum',
    'PTT max',
    'PTT mean',
    'PTT min',
    'PTT std',
    'PEEP max',
    'PEEP mean',
    'PEEP min',
    'PEEP std',
    'Fluid balance',
    'AdmissionCount',
    'SOFA score',
    'Age',
    'Gender',
    'Antibiotics',
    'Antiviral',
    'Antifungal',
]

obs_column_label_2 = [
    'RRmean (ABP) mean',
    'RRmean (NIBP) mean',
    'Leukozyten max',
    'Heartrate mean',
    'Heartrate std',
    'Glucose mean',
    'Respiratory Rate resp min',
    'Noradrenaline (Norepinefrine) max',
    'Thrombozyten max',
    'PTT max',
    'PEEP max',
    'Fluid balance',
    'SOFA score',
    'Age',
    'Gender',
    'Antibiotics',
]

obs_column_labels = [
    obs_column_label_0,
    obs_column_label_1,
    obs_column_label_2,
]

def get_column_labels(id):
    return {
        "id": "ID",
        "t":  "Length of Stay",
        "obs": obs_column_labels[id],
        "act": "Steroids",
        "rew": "ICU Mortality",
    }
